CREATE TABLE IF NOT EXISTS SPOTIFY_ACCOUNT (
    SPOTIFY_USER_ID VARCHAR(255) PRIMARY KEY,
    DISPLAY_NAME VARCHAR(255) NOT NULL,
    REFRESH_TOKEN VARCHAR(512) NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    VERSION BIGINT NOT NULL DEFAULT 0
);
